#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    mouse_follows_focus          on            \
    focus_follows_mouse          on            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               on            \
    window_shadow                on             \
    window_opacity               on            \
    window_opacity_duration      1.3            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.85           \
    window_border                on            \
    window_border_width          1              \
    active_window_border_color   0xFF94E2D5     \
    normal_window_border_color   0xFFF8BD96     \
    insert_feedback_color        0xFF94E2D5     \
    split_ratio                  0.50           \
    auto_balance                 on            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \
    top_padding                  2             \
    bottom_padding               0             \
    left_padding                 2             \
    right_padding                2             \
    window_gap                   4             \
    layout                       bsp

echo "yabai configuration loaded.."
