#!/usr/bin/env bash
alias ls='ls -CF --color=auto'
alias ks='ls -CF --color=auto'
alias ll='ls -al'
alias la='ls -A'
alias l='ls -CF'
alias rc='. ~/.bashrc'
alias gituntrack='git update-index --skip-worktree'
alias gittrack='git update-index --no-skip-worktree'
alias listuntracked='git ls-files -v . | grep ^S'
alias vi='vim'
alias ci='vi'
alias weather='curl wttr.in/Edmonton'
alias off='sudo shutdown -h now'
alias python=python3
alias airpods='echo -e "connect 40:E6:4B:3D:07:B9" | bluetoothctl'
alias airpods_trust='echo -e "trust 40:E6:4B:3D:07:B9" | bluetoothctl'
alias airpods_dis='echo -e "disconnect 40:E6:4B:3D:07:B9" | bluetoothctl'
alias screenseconds="xset dpms "
alias untrack="git update-index --assume-unchanged" 
alias track="git update-index --no-assume-unchanged" 
alias gen_tags="ctags --options=./ctags -R --verbose --exclude=node_modules* --exclude=dist-middle-tier --exclude=dist --languages=javascript,typescript"
