palette = "catppuccin_frappe"

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[♥](green) ❯](maroon)"
error_symbol = "[[✱](red) ❯](red)"
vimcmd_symbol = "[❮](green)"

[username]
show_always = true

[directory]
read_only = " 🔒 "
truncate_to_repo = false

[aws]
symbol = "🖥️ "

[nix_shell]
disabled = true

[time]
disabled = false
format = '[$time]($style) '
time_format = '%T'
utc_time_offset = '-6'

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
