#!/usr/bin/env python3
import fire
from scripts.install.install import Install
from scripts.install.rc_builder import RCBuilder
from scripts.secrets.secrets import Secrets
from scripts.status.status import Status

class tk(object):
    def __init__(self):
        self.secret = Secrets()
    def install(self, profile):
        Install().install(profile)
    def uninstall(self, profile):
        Install().uninstall(profile)
    def status(self):
        Status().display_status()


if __name__ == '__main__':
  fire.Fire(tk)